name: Deploy to Vercel

on:
  push:
    branches: [main]

env:
  VERCEL_ORG_ID: team_oxRYWCWiMgDp3gBxrjsTrXC7

jobs:
  deploy-admin:
    name: Deploy Unified Portal
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install --global vercel
      - run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_PROJECT_ID: prj_Y6l1fk3OryzqYgXsWjw0rA6fuhQL
      - run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_PROJECT_ID: prj_Y6l1fk3OryzqYgXsWjw0rA6fuhQL
